### ISSUE TITLE
作者你好，我使用了你的项目，并发出现了问题，能不能帮我看看

### ISSUE THREAD

**Issue by aaa359355126** [zuihou/lamp-cloud#159]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 8.0
Nacos(必填)：2.0.3

# 问题描述：
根据你的文档配置了，所有的服务器，正常运行没有问题的。我们这周一举行线下培训，大概了100人同时使用，然后再前端和后端不断出现熔断的情况，当人数减少的时候，系统又恢复正常。

# 报错截图
https://user-images.githubusercontent.com/75612486/175763020-ba51b7f3-1608-4ac5-bb43-d2ac56a09f83.png
我怀疑是熔断设置，请帮忙看看有没问题，nacos的common.yml
hystrix:
  threadpool:
    default:
      coreSize: 1000 # #并发执行的最大线程数，默认10
      maxQueueSize: 1000 # #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 # #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000  # 熔断超时 ribbon和hystrix是同时生效的，哪个值小哪个生效
    zuihou-file-server:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1200000

**Comment by aaa359355126** [comment]
java.lang.RuntimeException: could not acquire a semaphore for execution
    at com.netflix.hystrix.AbstractCommand.handleSemaphoreRejectionViaFallback(AbstractCommand.java:966)
    at com.netflix.hystrix.AbstractCommand.applyHystrixSemantics(AbstractCommand.java:554)
    at com.netflix.hystrix.AbstractCommand.access$200(AbstractCommand.java:60)
    at com.netflix.hystrix.AbstractCommand$4.call(AbstractCommand.java:419)
    at com.netflix.hystrix.AbstractCommand$4.call(AbstractCommand.java:413)
    at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
    at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
    at rx.Observable.unsafeSubscribe(Observable.java:10327)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.Observable.unsafeSubscribe(Observable.java:10327)
    at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
    at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.unsafeSubscribe(Observable.java:10327)
    at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
    at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
    at rx.Observable.unsafeSubscribe(Observable.java:10327)
    at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
    at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
    at rx.Observable.subscribe(Observable.java:10423)
    at rx.Observable.subscribe(Observable.java:10390)
    at rx.Observable.subscribe(Observable.java:10271)
    at org.springframework.cloud.gateway.filter.factory.HystrixGatewayFilterFactory$1.lambda$null$0(HystrixGatewayFilterFactory.java:141)
    at reactor.core.publisher.MonoCreate.subscr

**Comment by zuihou** [comment]
```yml

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true   # feign 熔断机制是否开启
    #支持压缩的mime types
  compression:  # 请求压缩
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:  # 响应压缩
      enabled: true

ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  ReadTimeout: 30000     #
  ConnectTimeout: 30000  # [ribbon超时时间]大于[熔断超时],那么会先走熔断，相当于你配的ribbon超时就不生效了  ribbon和hystrix是同时生效的，哪个值小哪个生效
  MaxAutoRetries: 0             # 最大自动重试
  MaxAutoRetriesNextServer: 1   # 最大自动像下一个服务重试
  OkToRetryOnAllOperations: false  #无论是请求超时或者socket read timeout都进行重试，

lamp-file-server:
  ribbon:
    ConnectTimeout: 300000
    ReadTimeout: 300000

hystrix:
  threadpool:
    default:
      coreSize: 1000 # #并发执行的最大线程数，默认10
      maxQueueSize: 1000 # #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 # #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000  # 熔断超时 ribbon和hystrix是同时生效的，哪个值小哪个生效
          semaphore:
            maxConcurrentRequests: 1000
    lamp-file-server:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1200000

```
maxConcurrentRequests 按需设置大点

参考： https://blog.csdn.net/wellven_chen/article/details/106757750
