### ISSUE TITLE
新建项目或者用代码生成器生成的项目启动后，日志中打印的端口为null，项目实际的端口为8080

### ISSUE THREAD

**Issue by zuihou** [zuihou/lamp-cloud#22]
**版本信息：**
源码版本：2.5.0
MySQL： 5.7.9
Nacos：1.2.1

**问题描述：**
新建项目或者用代码生成器生成的项目启动后，我在日志中打印的端口为null，项目实际的端口为8080。
1. 代码生成器 指定了12345 端口
```
public static void main(String[] args) {
        CodeGeneratorConfig config = new CodeGeneratorConfig();
        config
                // zuihou-admin-cloud 项目的 绝对路径！
                .setProjectRootPath(System.getProperty("user.dir"))
                // 项目的前缀
                .setProjectPrefix("alijiujiu-")

                // 需要新建的 服务名      该例会生成 zuihou-mall 服务
                .setServiceName("mall")

                // 子模块的设置请参考 消息服务 （msgs 服务下的 sms 模块即 视为子模块）
//                .setChildModuleName("hehe")

                // 生成代码的注释 @author zuihou
                .setAuthor("zuihou")
                // 项目描述
                .setDescription("商城")
                // 项目的版本， 一定要跟 zuihou-admin-cloud 下的其他服务版本一致， 否则会出错哦
                .setVersion("c.2.5.0-SNAPSHOT")
                // 服务的端口号
                .setServerPort("12345")
                // 项目的 groupId
                .setGroupId("com.github.zuihou")

        ;
        // 项目的业务代码 存放的包路径
        config.setPackageBase("com.alijiujiu.platform." + config.getChildModuleName());

        System.out.println("项目初始化根路径：" + config.getProjectRootPath());
        ProjectGenerator pg = new ProjectGenerator(config);
        pg.build();
    }
```
2. 生成成功并启动服务后，打印的端口为null
![image](https://user-images.githubusercontent.com/8500410/92327394-119fe280-f08c-11ea-8471-5f61ea99a55a.png)
3. 且swagger文档中也没有任何接口

## 支持一下:
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
出错原因：服务在启动时，没有读取到nacos中该服务的配置文件

解决方案：
1. 重启nacos
2. 在正确的命名空间中新建dm-persnal-server.yml配置文件 （这个文件名，取决于你新建服务的spring.appclication.name)
3. 将生成的项目src/main/resources目录下的 dm-persnal-server.yml 配置的内容复制到nacos
```
zuihou:
  swagger:
    enabled: true
    docket:
      tenant:
        title: xxx模块
        base-package: com.github.zuihou.xxxx.controller

server:
  port: 12345
```
4. 重启你新建的服务。

5. 重启后，端口能打印正确，但swagger文档还是没有显示出来，有3个原因
- 新建的服务中确实没有任何Controller接口
- 配置文件中base-package: com.github.zuihou.xxxx.controller 的路径没有配置正确
- 新建的服务依赖不正确， server层需要依赖 controller 层，才能加载controller层的接口

6. 若接口和端口都正确了， 直接访问服务可以显示接口，但通过gateway无法访问，则说明在gateway服务的配置文件中没有添加该服务的路由，加上即可。 如：
```
        - id: persnal
          uri: lb://dm-persnal-server
          predicates:
            - Path=/persnal/**
          filters:
            - StripPrefix=1
```
